### ISSUE TITLE
Support for `workerGroup` field

### ISSUE THREAD

**Issue by darkcrawler01** [coursera/dataduct#128]
WorkerGroup gives the flexibility of using existing EC2 instances and not spinning up new instance to do the work. From the reading the docs, I found that this valuable feature is not supported by `dataduct` yet. 
Any reason for not supporting this yet ? 

http://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/dp-how-task-runner-user-managed.html

**Comment by sb2nov** [comment]
@darkcrawler01 this is just something we haven't had a chance to build yet. But I'll keep it in mind for any future release of dataduct.

**Comment by sb2nov** [comment]
Fixed in #182

**Comment by darkcrawler01** [comment]
thanks ! i will try it out this weekend
