### ISSUE TITLE
Comments like `/* A /* B */` are not removed correctly

### ISSUE THREAD

**Issue by jhorowitz-coursera** [coursera/dataduct#134]
It appears that the comment-removal code in https://github.com/coursera/dataduct/blob/master/dataduct/database/parsers/transform.py#L50 will transform:
```
/* A /* B */
```
into
```
/* A
```
when it should really remove the entire thing.

**Comment by sb2nov** [comment]
Won't fix as this doesn't seem that important and comments should be written in some other fashion. Also even pyparsing's native cStypeComment parser doesn't support this case. 

Added more tests to mark this as unresolved in #183
