### ISSUE TITLE
Upsert steps don't work on tables with DOUBLE PRECISION columns

### ISSUE THREAD

**Issue by tanonev** [coursera/dataduct#155]
The upsert step failed with
`psycopg2.ProgrammingError: type "double" does not exist`
It looks like whatever is parsing the table SQL is assuming that the column type won't have any spaces in it.  For this particular case, a workaround exists because DOUBLE PRECISION, FLOAT8, and FLOAT are all aliases of each other, but there may be other cases for which this does not hold.

**Comment by cliu587** [comment]
fixed in https://github.com/coursera/dataduct/pull/180
