### ISSUE TITLE
Dataduct should state dependency on psycopg2 2.5 or greater

### ISSUE THREAD

**Issue by warhammerkid** [coursera/dataduct#164]
The changes in bad3afd1471f7c21975bb25a7609c2c79f1268a5 use the `cursor_factory` arg when calling `psycopg2.connect`, which was introduced in version 2.5 of psycopg2. I ran into this issue when using master to perform my pipeline activation and the `python-psycopg2` package for Ubuntu, which is only version 2.4.5. I'm guessing that adding this version constraint to `requirements.txt` will fix the problem once a new build is put up for pip.

**Comment by sb2nov** [comment]
Hi, https://github.com/coursera/dataduct/pull/165 should fix this issue. Thanks for catching it.
