### ISSUE TITLE
The create-load-redshift step should run with stage set to false

### ISSUE THREAD

**Issue by warhammerkid** [coursera/dataduct#167]
Currently this step downloads all input files to the local server, even though it does nothing with them. This is because `stage` is set to `'true'`, which implies that it needs the input files locally (see the [ShellCommandActivity docs](http://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/dp-object-shellcommandactivity.html#d0e24842) for details).

There is currently a pull request to fix this issue, but it does it by not passing in the input node, rather than correctly setting `stage` to false.

**Comment by cliu587** [comment]
I've made a PR for this: https://github.com/coursera/dataduct/pull/179

Thanks for the note!

**Comment by sb2nov** [comment]
Fixed in #179
