### ISSUE TITLE
supporting RDS Postgres

### ISSUE THREAD

**Issue by kpx-dev** [coursera/dataduct#204]
If I want to have Postgres support in dataduct (or is it already supported? sorry I'm new to dataduct), do I create something like this?
https://github.com/coursera/dataduct/blob/develop/dataduct/pipeline/mysql_node.py

Thanks!

**Comment by sb2nov** [comment]
You're right we'll have to create something like that. Ideally we would want to move from the mysql_node to a generic sql_node (http://docs.aws.amazon.com/datapipeline/latest/DeveloperGuide/dp-object-sqldatanode.html).

**Comment by kpx-dev** [comment]
I see, so create parent class like: SqlNode then make MysqlNode and PostgresNode inherit from it? If you are cool with this support, I'll try to submit such PR?

**Comment by sb2nov** [comment]
Yeah that makes sense, feel free to send in a PR.
