### ISSUE TITLE
Can I get config file currently version?

### ISSUE THREAD

**Issue by sungjuly** [coursera/dataduct#30]
It looks like an awesome project. So I'm trying to test this. However, I couldn't find relevant config files[1] and docs. Can I get config file currently version? And can you tell me how to run it? ;)

```
git clone project_path
python setup.py install
cp examples/example_load_redshift.yaml ~/<my_path>
cd ~/<my_path>
dataduct pipeline create * - Where is generated json file on local?
```

[1] Irrelevant config: https://github.com/coursera/dataduct/blob/develop/dataduct/config/example_config

**Comment by sb2nov** [comment]
Hi @sungjuly, thanks for bringing this up. I'll update the docs and in a few days.

**Comment by sungjuly** [comment]
@sb2nov Thanks

**Comment by sb2nov** [comment]
@sungjuly http://dataduct.readthedocs.org/en/latest/config.html
