### ISSUE TITLE
Which step do you generally use to work with redshift at coursera? (create-load-redshift or load-redshift)

### ISSUE THREAD

**Issue by sungjuly** [coursera/dataduct#43]
I realized that the RedshiftActivity is useful for easy workflow or options. However, if I want to do work with IDENTIFY(auto increase) or null values this wrapper does not work. Because this use temp table and then select-insert. (Might be redshift bug or limitation)

So this problems, you guys made create-load-redshift to resolve this problem, right?
I'm wondering which step do you generally use to work with redshift at coursera? (create-load-redshift or load-redshift)

**Comment by sb2nov** [comment]
@sungjuly yeah we ended up creating shell-command-activity steps like create-load-redshift for the same reason you mentioned. Also load-redshift assumes that the table is already created when running the etl for the first time, this was an additional step in creating an etl so we moved that logic into the create-load-redshift step. 

Closing the issue but feel free to ask more details about it.
